LU-17793 libcfs: fix objtool warning in lbug_with_loc()
After lbug_with_loc() was removed from the objtool
global_noreturns array in Linux commit v6.4-rc2-10-g34245659debd,
building Lustre hit the following warning:

  libcfs/libcfs/fail.o: warning: objtool: __cfs_fail_check_set()
  falls through to next function __cfs_fail_timeout_set()

This patch fixes the above warning by adding an unreachable
panic() at the end of lbug_with_loc() to terminate all of
the call paths in that function.

As a consequence of this change, we need to make the patch
fix more errors, such as:

  lnet/lnet/api-ni.c: In function 'lnet_res_type2str':
  libcfs/include/libcfs/libcfs_private.h:119:9:
  error: this statement may fall through [-Werror=implicit-fallthrough=]
    119 |         lbug_with_loc(&msgdata); \
        |         ^~~~~~~~~~~~~~~~~~~~~~~
  lnet/lnet/api-ni.c:1143:17: note: in expansion of macro 'LBUG'
   1143 |                 LBUG();
        |                 ^~~~
  lnet/lnet/api-ni.c:1144:9: note: here
   1144 |         case LNET_COOKIE_TYPE_MD:
        |         ^~~~

and

  lustre/obdclass/lprocfs_status.c: In function 'lprocfs_stats_lock':
  lustre/obdclass/lprocfs_status.c:470:1:
  error: control reaches end of non-void function [-Werror=return-type]
    470 | }
        | ^

Lustre-change: https://review.whamcloud.com/55505
Lustre-commit: 9f44a48b365924ee6f576c95bf0649160b6be58a

LU-18445 libcfs: Remove msleep before panic for lbug

If panic on lbug is set, do not sleep before calling
the panic() as it has very undesirable side effects.
Logs are getting rotated, racing threads continue moving
and get harder to understand what they were doing and
so on.

Lustre-change: https://review.whamcloud.com/57010
Lustre-commit: 83f62e0dee9447919b7fbcf60eea0e6b0c503930

Fixes: 9f44a48b365 ("LU-17793 libcfs: fix objtool warning in lbug_with_loc()")
Signed-off-by: Oleg Drokin <green@whamcloud.com>
Was-Change-Id: Idd49bda78c6441a11d3ea18cb053fd9755552604

Signed-off-by: Jian Yu <yujian@whamcloud.com>
Change-Id: I5574559619b4b6746f4e7da51f3213ede246a73b